### ISSUE TITLE
Support other binary caches next to cachix

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#125]
Some generic `nix copy` would be great We might need some secret support for things like s3 credentials or ssh keys.

**Comment by mannp** [comment]
Fwiw I have a private attic cache to s3 now getting updated following buildbot builds and it works pretty well 🙂

**Comment by Mic92** [comment]
Did you integrated it into buildbot-nix or is this some solution that watches the store?

**Comment by mannp** [comment]
> Did you integrated it into buildbot-nix or is this some solution that watches the store?

Not being a Python dev sadly not integrated, just a systemd service utilising the 'attic watch-store' command.

**Comment by Mic92** [comment]
If you have some snippets to share, we can still have it in the documentation today until we have support for something else.

**Comment by Mic92** [comment]
If you have your configuration somewhere, we can link to it. Otherwise, a module could go into `./examples`

**Comment by mannp** [comment]
> If you have your configuration somewhere, we can link to it. Otherwise, a module could go into `./examples`

My config is not public but have attempted an example.

https://github.com/nix-community/buildbot-nix/pull/187

**Comment by MagicRB** [comment]
#229 allows to add arbitrary post build steps, which may close this PR depending on how we want things, therefore closing and feel very free to reopen :) (or ask for a reopen)
