### ISSUE TITLE
Rework GITHUB_TOKEN support so we only need a github app

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#127]
It's a lot less friction to just be able to create a github app and install it in an organization.
A github app can also request a time-bound github token like this: https://github.com/NixOS/nixpkgs-merge-bot/blob/cae47034242b6604db5199a73e5f4ce5121ffa74/nixpkgs_merge_bot/github/GitHubClient.py#L249
It needs to be regularly refreshed

**Comment by MagicRB** [comment]
This has been implemented in #156  and can be closed. So closing.
