### ISSUE TITLE
Fine-Grained Personal Access Tokens don't need `repo:admin`

### ISSUE THREAD

**Issue by lorenzleutgeb** [nix-community/buildbot-nix#153]
`README.md` assumes "classic" PATs. During set up of buildbot-nix, @Erethon and me noticed that it would probably be enough to create a [Fine-Grained Personal Access Token](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/) with the following permissions for the buildbot GitHub Account:

 - [Repository Permissions for "Webhooks"](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens#repository-permissions-for-webhooks) (read and write).
 - [Repository Permissions for "Commit Statuses"](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens#repository-permissions-for-commit-statuses) (read and write).
 - [Repository Permissions for "Contents"](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens#repository-permissions-for-contents) (read). We are configuring a public repo, so did not have to set this, but I guess that this is what would be needed for a private repo. [StackOverflow](https://stackoverflow.com/a/74496280/1835188) seems to agree.

The account also needs ["Write" Permissions on the repository](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization). This seems to work fine. What's preventing their use is an explicit check in buildbot-nix that guards repository discovery:

https://github.com/Mic92/buildbot-nix/blob/077a60a5d040f7161c50a83d827db77a2a68ed9f/buildbot_nix/github_projects.py#L270-L274

This checking method is incompatible with Fine-Grained PATs. The response looks like this:

```json
{ "permissions": { "admin": false, "maintain": false, "push": false, "triage": false, "pull": true } }
```

One downside of Fine-Grained PATs is that such a check [apparently cannot be implemented](https://github.com/orgs/community/discussions/73397).

However, in case buildbot runs into a HTTP 401, it cloud also expose the contents of the response header `X-Accepted-GitHub-Permissions` in the logs:

> To help you choose the correct permissions, you will receive the `X-Accepted-GitHub-Permissions` header in the REST API response. The header will tell you what permissions are required in order to access the endpoint.

A benefit is that, well, it's true that permissions can be set in a much more fine grained way. It avoids having to give the bot user account admin permissions on the repo(s).

Our workaround was to switch buildbot from a "classic" PAT to a Fine-Grained PAT after it had installed the Webhook. Another option would of course be to patch away the above check.

Here's how that looks in Org settings at `https://github.com/organizations/${NAME}/settings/personal-access-tokens/`:

![image](https://github.com/Mic92/buildbot-nix/assets/542154/838901ad-b180-4747-8231-1e46a9242034)

**Comment by Mic92** [comment]
@MagicRB is it still on your agenda to convert buildbot-nix into only using the GitHub app for everything?

**Comment by MagicRB** [comment]
Yep, I should get to it this weekend

> @MagicRB is it still on your agenda to convert buildbot-nix into only using the GitHub app for everything?

**Comment by Mic92** [comment]
@MagicRB you can steal the code for re-newing GITHUB_TOKEN's from an github app from here: https://github.com/NixOS/nixpkgs-merge-bot/blob/1aad9bf9b570889da6555650f82d670fc2f73658/nixpkgs_merge_bot/github/GitHubClient.py#L218

**Comment by lorenzleutgeb** [comment]
Sounds like #127?

**Comment by MagicRB** [comment]
The PR exists, the code is in place, a mess has been created: #156

Next step: refactoring

**Comment by MagicRB** [comment]
@lorenzleutgeb #156  is in place, is that enough for your use case? Or do you still desire file-grained PATs?

**Comment by Mic92** [comment]
I believe so. Otherwise feel free to re-open this.
