### ISSUE TITLE
Org members cannot stop builds

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#175]
Reported by @nikstur in nix-community

**Comment by nikstur** [comment]
It was me @nikstur

**Comment by nikstur** [comment]
It also seems that if you manually rebuild, `nix-eval` will not turn green: https://buildbot.nix-community.org/#/builders/21/builds/57

**Comment by Mic92** [comment]
I think buildbot doesn't send out a status update in that case. I would probably ignore this bug for now and people need to restart the "nix-eval" instead.

**Comment by MagicRB** [comment]
I need more information here, testing it on the link you sent, I can both rebuild and cancel. So not sure how to reproduce and debug why. According to the current code, anyone in the organization that the project belongs to should be able to control the `nix-eval`, `nix-build` and `nix-skipped-build` builders.

**Comment by Mic92** [comment]
I will try to get the logs for that soon, if not please ping me again.

**Comment by Mic92** [comment]
So the issue is that the "eval" builder can be restarted but not the triggered package builds.
Here are the logs for lanzaboote:

```
Jun 14 22:07:12 build03 twistd[2502]: 2024-06-14T22:07:12+0000 [buildbot_nix#warn] Builder github:nix-community/lanzaboote#checks.aarch64-linux.basic not allowed by nix-community: {'nix-community/nix-index/nix-eval', 'nix-community/neovim-nightly-overlay/nix-skipped-build', 'nix-community/nixvim/nix-build', 'nix-community/ethereum.nix/nix-eval', 'nix-community/infra/nix-skipped-build', 'nix-community/nixpkgs-xr/nix-skipped-build', 'nix-community/nixos-images/nix-build', 'nix-community/nixpkgs-update/nix-skipped-build', 'nix-community/nixpkgs-xr/nix-eval', 'nix-community/srvos/nix-build', 'nix-community/nix-index/nix-skipped-build', 'nix-community/srvos/nix-eval', 'nix-community/nixos-images/nix-skipped-build', 'nix-community/nixpkgs-update/nix-build', 'nix-community/dreampkgs/nix-skipped-build', 'nix-community/ethereum.nix/nix-build', 'nix-community/nix-direnv/nix-eval', 'nix-community/nixpkgs-xr/nix-build', 'nix-community/nixvim/nix-eval', 'nix-community/nixvim/nix-skipped-build', 'nix-community/lanzaboote/nix-build', 'nix-community/srvos/nix-skipped-build', 'nix-community/dream2nix/nix-skipped-build', 'nix-community/infra/nix-build', 'nix-community/dreampkgs/nix-eval', 'nix-community/dream2nix/nix-eval', 'nix-community/neovim-nightly-overlay/nix-eval', 'nix-community/nix-direnv/nix-build', 'nix-community/nixos-generators/nix-build', 'nix-community/lanzaboote/nix-eval', 'nix-community/dream2nix/nix-build', 'nix-community/nixos-generators/nix-eval', 'nix-community/infra/nix-eval', 'nix-community/nix-index/nix-build', 'nix-community/nixos-images/nix-eval', 'nix-community/nixos-generators/nix-skipped-build', 'reload-github-projects', 'nix-community/ethereum.nix/nix-skipped-build', 'nix-community/neovim-nightly-overlay/nix-build', 'nix-community/nix-direnv/nix-skipped-build', 'nix-community/lanzaboote/nix-skipped-build', 'nix-community/nixpkgs-update/nix-eval', 'nix-community/dreampkgs/nix-build'}
```

**Comment by MagicRB** [comment]
> It also seems that if you manually rebuild, `nix-eval` will not turn green: https://buildbot.nix-community.org/#/builders/21/builds/57

This seems to be a feature? of buildbot, not sure how much we can do there. The logic of this is handled [here](https://github.com/buildbot/buildbot/blob/331121358ba547a6d445de8760c5c8d359171cf8/master/buildbot/data/buildsets.py#L235) and [here](https://github.com/buildbot/buildbot/blob/331121358ba547a6d445de8760c5c8d359171cf8/master/buildbot/process/results.py#L40).

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/buildbot-nix/pull/205
