### ISSUE TITLE
Reporting issue when there are too many checks

### ISSUE THREAD

**Issue by zimbatm** [nix-community/buildbot-nix#178]
Buildbot is hitting some rate limit. I noticed that as treefmt-nix grew, it started having issues reporting build statuses.

Eg: https://github.com/numtide/treefmt-nix/pull/185#event-13122681218
![image](https://github.com/nix-community/buildbot-nix/assets/3248/f2c093f0-97e0-4407-8989-c6602719457d)

```
Jun 11 20:10:59 bld2 twistd[2847473]: 2024-06-11T20:10:59+0000 [HTTP11ClientProtocol (BufferingTLSTransport),client] Failed to update "success" for numtide/treefmt-nix at b303c743d853af36b8bd75b4d83b48ed7ab0747a, context "buildbot/nix-build .#checks.aarch64-linux.formatter-rufo", issue 185. http 403, b'{\n  "documentation_url": "https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits",\n  "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID 9748:27DC3C:961101D:9705126:6668AF52."\n}'
Jun 11 20:10:59 bld2 twistd[2847473]:         Traceback (most recent call last):
Jun 11 20:10:59 bld2 twistd[2847473]:           File "/nix/store/w869q04ijifzfax4hysjvnall3kgah6d-python3-3.11.9-env/lib/python3.11/site-packages/twisted/internet/defer.py", line 1078, in _runCallbacks
Jun 11 20:10:59 bld2 twistd[2847473]:             current.result = callback(  # type: ignore[misc]
Jun 11 20:10:59 bld2 twistd[2847473]:           File "/nix/store/w869q04ijifzfax4hysjvnall3kgah6d-python3-3.11.9-env/lib/python3.11/site-packages/twisted/internet/defer.py", line 1949, in _gotResultInlineCallbacks
Jun 11 20:10:59 bld2 twistd[2847473]:             _inlineCallbacks(r, gen, status, context)
Jun 11 20:10:59 bld2 twistd[2847473]:           File "/nix/store/w869q04ijifzfax4hysjvnall3kgah6d-python3-3.11.9-env/lib/python3.11/site-packages/twisted/internet/defer.py", line 2003, in _inlineCallbacks
Jun 11 20:10:59 bld2 twistd[2847473]:             result = context.run(gen.send, result)
Jun 11 20:10:59 bld2 twistd[2847473]:           File "/nix/store/w869q04ijifzfax4hysjvnall3kgah6d-python3-3.11.9-env/lib/python3.11/site-packages/buildbot/reporters/github.py", line 234, in sendMessage
Jun 11 20:10:59 bld2 twistd[2847473]:             log.err(
Jun 11 20:10:59 bld2 twistd[2847473]:         --- <exception caught here> ---
Jun 11 20:10:59 bld2 twistd[2847473]:           File "/nix/store/w869q04ijifzfax4hysjvnall3kgah6d-python3-3.11.9-env/lib/python3.11/site-packages/buildbot/reporters/github.py", line 222, in sendMessage
Jun 11 20:10:59 bld2 twistd[2847473]:             raise RuntimeError()
Jun 11 20:10:59 bld2 twistd[2847473]:         builtins.RuntimeError:
```

**Comment by Mic92** [comment]
What hercules-ci instead does is just reporting 3 statuses: one for eval, one for all packages beeing build and one for effects.
Maybe we should do the same.

**Comment by MagicRB** [comment]
i think having all of them is nice, as long as there isnt too many of them, so maybe make it conditional on the number of checks. but this is again an upstream cooperative change, or an ugly hack :)

**Comment by Mic92** [comment]
Subclassing a reporter might be an option... It wouldn't be that ugly of an hack. I don't know the exact api of a reporter but in pseudo code it would look something like this:

```
class GithubStatusReporter(buildbot.GithubStatusReporter):
  def report(args...):
    if some_filter():
        return
    super().report(args...)
```

**Comment by MagicRB** [comment]
I'll look into this properly, i have a few ideas but im not sured which one will end up being the sanest of them.

**Comment by Mic92** [comment]
worst comes to worst, we can still just call the api ourself as needed. I don't think the api is that complicated after all and it would also allows us to add things like the last log lines to pull request like garnix does.

**Comment by Mic92** [comment]
Ok. Here an idea two solve two problems at once: Fixing too many ci status items and making the resulting summary easier to read/search:

We during the build only show the eval status and update that one to show the current build progress, i.e.

- buildbot/nix-eval — Evaluation started...
- buildbot/nix-eval — Build 2/10, 2 failure

Have another build step that comes afterwards that reports the build process of all builds in an html log.

```
- buildbot/nix-build — Build done. <Link> to HTML summary
```

In the summary we can than link to all previous builds, but sort the failed ones first.

**Comment by Mic92** [comment]
We would than also only mark "nix-eval" as failed if it's evaluation actually failed and have a separate status for builds, which is overall more intuitive.

**Comment by zimbatm** [comment]
Before doing anything, it would be good to find out which of the secondary rate limits we're hitting: https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits

> Make too many concurrent requests. No more than 100 concurrent requests are allowed. This limit is shared across the REST API and GraphQL API.

Is it possible that the python client has no concurrency limit?

> Create too much content on GitHub in a short amount of time. In general, no more than 80 content-generating requests per minute and no more than 500 content-generating requests per hour are allowed.

That might be the other reason. I'm not sure if the status checks count as content. Also, we generated 185 of them.

**Comment by Mic92** [comment]
I think it would be over all good to limit the number of statues. I.e. the gitea ui also doesn't scale well with many status items as not all views allow to scroll.

**Comment by MagicRB** [comment]
I'm looking into this, GitHub will tell us what primary rate limit we're hitting, but not which secondary one. I'll instrument the code to count the number of requests made to GitHub and also properly interpret the ratelimit so we may get further insight into this problem.

**Comment by MagicRB** [comment]
```
Jul 08 11:52:28 buildbot twistd[305]: 2024-07-08T11:52:28+0000 [HTTP11ClientProtocol (BufferingTLSTransport),client] Failed to update "success" for nc-mirror-buildbot/treefmt-nix at 79d65404d7d6f809b328bcd0da79d7af5b459cfd, context "buildbot/nix-build .#checks.x86_64-linux.formatter-ktlint", issue None. http n/a, n/a
Jul 08 11:52:28 buildbot twistd[305]:         Traceback (most recent call last):
Jul 08 11:52:28 buildbot twistd[305]:           File "/nix/store/0c9sfzfhma1ckfa5cd6cgkm14bmh8wcs-python3-3.11.9-env/lib/python3.11/site-packages/twisted/internet/defer.py", line 1949, in _gotResultInlineCallbacks
Jul 08 11:52:28 buildbot twistd[305]:             _inlineCallbacks(r, gen, status, context)
Jul 08 11:52:28 buildbot twistd[305]:           File "/nix/store/0c9sfzfhma1ckfa5cd6cgkm14bmh8wcs-python3-3.11.9-env/lib/python3.11/site-packages/twisted/internet/defer.py", line 1999, in _inlineCallbacks
Jul 08 11:52:28 buildbot twistd[305]:             result = context.run(
Jul 08 11:52:28 buildbot twistd[305]:           File "/nix/store/0c9sfzfhma1ckfa5cd6cgkm14bmh8wcs-python3-3.11.9-env/lib/python3.11/site-packages/twisted/python/failure.py", line 519, in throwExceptionIntoGenerator
Jul 08 11:52:28 buildbot twistd[305]:             return g.throw(self.value.with_traceback(self.tb))
Jul 08 11:52:28 buildbot twistd[305]:           File "/nix/store/0c9sfzfhma1ckfa5cd6cgkm14bmh8wcs-python3-3.11.9-env/lib/python3.11/site-packages/buildbot/reporters/github.py", line 234, in sendMessage
Jul 08 11:52:28 buildbot twistd[305]:             log.err(
Jul 08 11:52:28 buildbot twistd[305]:         --- <exception caught here> ---
Jul 08 11:52:28 buildbot twistd[305]:           File "/nix/store/0c9sfzfhma1ckfa5cd6cgkm14bmh8wcs-python3-3.11.9-env/lib/python3.11/site-packages/buildbot/reporters/github.py", line 208, in sendMessage
Jul 08 11:52:28 buildbot twistd[305]:             response = yield self.createStatus(repo_user=repo_owner,
Jul 08 11:52:28 buildbot twistd[305]:         twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
Jul 08 11:52:28 buildbot twistd[305]:
```
got a different error on the first run, I probably haven't hit the ratelimit yet.

**Comment by MagicRB** [comment]
I managed to hit the ratelimit after roughly 800 ish status updates, so i think we're hitting something there. It's really hard to tell what precisely, I think your best bet here is to verify if they send a 'retry after n minutes' header and if so, we 'retry after n minutes'

**Comment by MagicRB** [comment]
```
Headers({
  b'date': [b'Mon, 08 Jul 2024 14:19:32 GMT'],
  b'content-type': [b'application/json; charset=utf-8'],
  b'x-ratelimit-limit': [b'5000'],
  b'x-ratelimit-remaining': [b'0'],
  b'x-ratelimit-reset': [b'1720449546'],
  b'x-ratelimit-used': [b'5000'],
  b'x-ratelimit-resource': [b'core'],
  b'x-github-media-type': [b'github.v3; format=json'],
  b'access-control-expose-headers': [
    b'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset'
  ],
  b'access-control-allow-origin': [b'*'],
  b'strict-transport-security': [
    b'max-age=31536000; includeSubdomains; preload'
  ],
  b'x-frame-options': [b'deny'],
  b'x-content-type-options': [b'nosniff'],
  b'x-xss-protection': [b'0'],
  b'referrer-policy': [
    b'origin-when-cross-origin, strict-origin-when-cross-origin'
  ],
  b'content-security-policy': [b"default-src 'none'"],
  b'vary': [b'Accept-Encoding, Accept, X-Requested-With'],
  b'server': [b'github.com'],
  b'x-github-request-id': [b'####']}),
  'log_time': 1720448372.7841113
}
API rate limit exceeded for installation ID 51813639. If you reach out to GitHub Support for help, please include the request ID #### and timestamp 2024-07-08 14:19:32 UTC.
status: 403
```
I hit a primary rate limit, but I can work with this.

**Comment by Mic92** [comment]
It looks like in treefmt-nix we have way less than 800 status updates and some nix builds seems to never get green in github, also they already are finished on buildbots site: https://github.com/numtide/treefmt-nix/pull/195

**Comment by Mic92** [comment]
You can see the same behavior in other recent builds of buildbot-nix in treefmt-nix

**Comment by MagicRB** [comment]
they're all cumulative across the whole app, the ratelimits afaik. So if the buildbot instance is doing more than treefmt on that token, it will still hit it. It also depends on how many repos it is hooked up to, theoretically my bulidbot is installed into 80~ repositories. (I have a lot of stuff on GitHub).

**Comment by Mic92** [comment]
If we hit rate limits there, it probably also break other stuff where the API is used. I think we should think about reducing the number of status updates as well.

**Comment by MagicRB** [comment]
definitely, definitely, just bandaging this specific part up, ideally we'd upstream actual ratelimit handling and retries to buildbot

**Comment by Mic92** [comment]
Yes. Surely they would accept that.

**Comment by MagicRB** [comment]
If we're going the upstream route it'll take me a while because I haven't done anything remotely like this before. But I'll look into how its suppoaed to be done in the Pythonic world.

**Comment by MagicRB** [comment]
After an extensive look at the code, evaluating all possible options. Retries will be hard to implement. `HTTPClientService` from buildbot uses either `treq` or `txrequests`, `treq` does not support retries at *all*, i tried to hack it together but [`IBodyProducer`](https://docs.twistedmatrix.com/en/stable/api/twisted.web.iweb.IBodyProducer.html) does not support rolling back so it must be copied, but it has no copy method. I tried to match on the concrete instance, namely [`FileBodyProducer`](https://docs.twistedmatrix.com/en/stable/api/twisted.web.client.FileBodyProducer.html) and pull out the file descriptor and dup that, but I immediately got `Operation not supported` errors, so that's not the way. `txrequests` does support retries apparently but according to buildbots own comments is [2.8x slower](https://github.com/buildbot/buildbot/blob/347a8834dc9d53db6ffceb09830a45a444fd31cd/master/buildbot/util/httpclientservice.py#L98). I'm really not sure how to proceed here, we're fighting with `twisted` every step of the way here.

If we want to do retries globally and catch all requests to GitHub, we need to switch to `txrequests` or switch away from `twisted`  (which is impossible since that's what upstream uses)

**Comment by MagicRB** [comment]
There are only 4 ways forward:
- load the whole body into memory and feed it into the socket from there -> DoS problem
- switch to `txrequests` -> slow
- pull apart twisted **completely**
- find something which works with `twisted` but is better implemented

**Comment by Mic92** [comment]
why does the http library needs to supports retries. Is it not possible to add logic around it?

**Comment by MagicRB** [comment]
I was attempting to make sure that we catch any and all outgoing requests to github. We could of course implement it at a higher level, but I wanted to avoid that if possible.

**Comment by zimbatm** [comment]
Solution (5): reduce the number of checks that are getting reported :)

**Comment by MagicRB** [comment]
I'm working on that now :) i wanted to first check whether we can handle the ratelimits properly, because we can still hit them even with reducing. It makes it just less likely. And I've seen GitHub throw me back a random error code at random, so that would be nice to catch too.

**Comment by MagicRB** [comment]
(the reducing is almost done, just need to finish and clean up)
