### ISSUE TITLE
Rebuild a "cached failure" step should try a proper rebuild

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#287]
While the "rebuild" button works on the whole matrix, it doesn't work, when we select a single build.

**Comment by MagicRB** [comment]
I'm not sure if this is possible to implement, but I'll check

**Comment by MagicRB** [comment]
Okay so I dug into this and implementing it so that it reruns the build is possible. What im not sure is possible is to make it also recompute the overall build status, so the `nix-build` report. I'll so as much as is reasonably doable and then we see if we want more.

**Comment by MagicRB** [comment]
That was exactly my idea, the PR that I opened implements that. It just doesn't actually update the reports or anything like that currently.
