### ISSUE TITLE
use github's status check api rather than statuses api

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#327]
Status check api allows more fancy features like log output and a restart button.
Also mergify recently stopped looking at `commit status` updates for merging.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks

**Comment by zowoq** [comment]
Same as https://github.com/nix-community/buildbot-nix/issues/236?

**Comment by Mic92** [comment]
Yes.
